import { useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';

import CldCamera from '@components/CldCamera';

import styles from '@styles/Home.module.scss'

const availableFilters = [
  'al_dente',
  'athena',
  'audrey',
  'aurora',
  'daguerre',
  'eucalyptus',
  'fes',
  'frost',
  'hairspray',
  'hokusai',
  'incognito',
  'linen',
  'peacock',
  'primavera',
  'quartz',
  'red_rock',
  'refresh',
  'sizzle',
  'sonnet',
  'ukulele',
  'zorro'
]

export default function Home() {
  const [filter, setFilter] = useState();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <CldCamera className={styles.camera} filter={filter} />
        <h2>Filters</h2>
        <ul>
          {availableFilters.map(filter => {
            return (
              <li key={filter}>
                <button onClick={() => setFilter(filter)}>{ filter }</button>
              </li>
            )
          })}
        </ul>
      </main>
    </div>
  )
}